name: Man10EconomyNote
version: 1.0
main: red.man10.man10economynote.Man10EconomyNote
authors: [Sho0]
depend:
 - Man10OfflineBank
api-version: 1.16
commands:
 mlend:
 mcheque:
 mchequeop:
 mviewdebt:
 man10economynote: